#!/bin/sh
sudo nixos-rebuild switch --flake .\#nixos;



==============================================================================
blink.cmp:                                                                1 ⚠️

System ~
- ✅ OK curl is installed
- ✅ OK git is installed
- ✅ OK Your system is supported by pre-built binaries (x86_64-unknown-linux-gnu)
- ✅ OK blink_cmp_fuzzy lib is downloaded/built

Sources ~
- ⚠️ WARNING Some providers may show up as "disabled" but are enabled dynamically (e.g. cmdline)

Default sources ~
- lsp (blink.cmp.sources.lsp)
- path (blink.cmp.sources.path)
- snippets (blink.cmp.sources.snippets)
- buffer (blink.cmp.sources.buffer)
- dadbod (vim_dadbod_completion.blink)

Cmdline sources ~
- buffer (blink.cmp.sources.buffer)
- cmdline (blink.cmp.sources.cmdline)

Disabled sources ~
- lazydev (lazydev.integrations.blink)
- omni (blink.cmp.sources.complete_func)

==============================================================================
conform:                                                                  6 ⚠️

conform.nvim report ~
- Log file: /home/muneeb/.local/state/nvim/conform.log
- ✅ OK csharpier ready (cs)
- ⚠️ WARNING dart_format unavailable: Command 'dart' not found
- ✅ OK fantomas ready (fsharp)
- ⚠️ WARNING fish_indent unavailable: Command 'fish_indent' not found
- ✅ OK gofumpt ready (go)
- ✅ OK goimports ready (go)
- ✅ OK ktlint ready (kotlin)
- ⚠️ WARNING markdown-toc unavailable: Condition failed
- ⚠️ WARNING markdownlint-cli2 unavailable: Condition failed
- ✅ OK nixfmt ready (nix)
- ✅ OK oxfmt ready (typescript, vue, svelte, json, javascript, typescriptreact, javascriptreact, jsonc, astro)
- ✅ OK php_cs_fixer ready (php)
- ⚠️ WARNING prettier unavailable: Command 'prettier' not found
- ✅ OK shfmt ready (sh)
- ⚠️ WARNING sqlfluff unavailable: Root directory not found
- ✅ OK stylua ready (lua)
- ✅ OK twig-cs-fixer ready (twig)

==============================================================================
easy-dotnet:                                                        2 ⚠️  1 ❌

General information ~
- Linux (7.1.5-zen1)
- Neovim version: 0.12.4
- Shell: /nix/store/l0wcagwxgg5vdsklbci9zf9rh71b0kw4-zsh-5.9.2/bin/zsh
- Commit: 0ebe09313dca2a6d4c354ab7df8e1687c2021d13

Dotnet information ~
- dotnet version: 11.0.100-preview.6.26359.118
- Installed SDKs:
- 6.0.428 [/nix/store/mk6zk3vhpdzj2zivn4jivp2qhpj74xhg-dotnet-combined/share/dotnet/sdk]
- 7.0.410 [/nix/store/mk6zk3vhpdzj2zivn4jivp2qhpj74xhg-dotnet-combined/share/dotnet/sdk]
- 8.0.423 [/nix/store/mk6zk3vhpdzj2zivn4jivp2qhpj74xhg-dotnet-combined/share/dotnet/sdk]
- 9.0.316 [/nix/store/mk6zk3vhpdzj2zivn4jivp2qhpj74xhg-dotnet-combined/share/dotnet/sdk]
- 10.0.302 [/nix/store/mk6zk3vhpdzj2zivn4jivp2qhpj74xhg-dotnet-combined/share/dotnet/sdk]
- 11.0.100-preview.6.26359.118 [/nix/store/mk6zk3vhpdzj2zivn4jivp2qhpj74xhg-dotnet-combined/share/dotnet/sdk]

easy-dotnet CLI dependencies ~
- ✅ OK dotnet is installed
- ✅ OK dotnet-easydotnet is installed
- ⚠️ WARNING dotnet ef is not installed
  - ADVICE:
    - dotnet tool install --global dotnet-ef

easy-dotnet lua dependencies ~
- ✅ OK plenary installed
- ⚠️ WARNING dap not installed
  - ADVICE:
    - Some functionality will be disabled
    - https://github.com/mfussenegger/nvim-dap

Treesitter Indentation ~
- ✅ OK c_sharp parser is installed
- ❌ ERROR Failed to run healthcheck for "easy-dotnet" plugin. Exception:
  ...re/nvim/lazy/easy-dotnet.nvim/lua/easy-dotnet/health.lua:282: Vim:E95: Buffer with this name already exists


==============================================================================
lazy:                                                                     2 ⚠️

lazy.nvim ~
- {lazy.nvim} version `11.17.5`
- ✅ OK {git} `version 2.55.0`
- ⚠️ WARNING found existing packages at `/home/muneeb/.local/share/nvim/site/pack/core`
- ✅ OK packer_compiled.lua not found

luarocks ~
- checking `luarocks` installation
- ✅ OK no plugins require `luarocks`, so you can ignore any warnings below
- ✅ OK {luarocks} `/nix/store/xbdzyf7nfb5ylzq4b8kxywqaxiq4glrk-lua5.2-luarocks-3.13.0-1/luarocks-3.13.0-1-rocks/luarocks/3.13.0-1/bin/luarocks 3.13.0`
- ⚠️ WARNING {lua5.1} or {lua} or {lua-5.1} version `5.1` not installed

==============================================================================
lazyvim:                                                                  1 ⚠️

LazyVim ~
- ✅ OK Using Neovim >= 0.11.2
- ✅ OK `git` is installed
- ✅ OK `rg` is installed
- ✅ OK `fd` is installed
- ⚠️ WARNING `lazygit` is not installed
- ✅ OK `fzf` is installed
- ✅ OK `curl` is installed

LazyVim nvim-treesitter ~
- ✅ OK `C compiler` is installed
- ✅ OK `curl` is installed
- ✅ OK `tar` is installed
- ✅ OK `tree-sitter (CLI)` is installed

==============================================================================
lspconfig:                                                                  ✅

- Skipped. This healthcheck is redundant with `:checkhealth vim.lsp`.

==============================================================================
mason:                                                                    4 ⚠️

mason.nvim ~
- ✅ OK mason.nvim version v2.3.1
- ✅ OK PATH: prepend
- ✅ OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- ✅ OK neovim version >= 0.10.0

mason.nvim [Registries] ~
- ✅ OK Registry `github.com/mason-org/mason-registry version: 2026-08-14-regal-cheetah` is installed.
- ✅ OK Registry `SynthesizedRegistrySource` is installed.

mason.nvim [Core utils] ~
- ✅ OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- ✅ OK wget: `GNU Wget 1.25.0, a non-interactive network retriever.`
- ✅ OK curl: `curl 8.21.0 (x86_64-pc-linux-gnu) libcurl/8.21.0 OpenSSL/3.6.3 zlib/1.3.2 brotli/1.2.0 zstd/1.5.7 libidn2/2.3.8 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.69.0 ngtcp2/1.23.0 nghttp3/1.16.0 mit-krb5/1.22.2`
- ✅ OK gzip: `gzip 1.14`
- ✅ OK tar: `tar (GNU tar) 1.35`
- ✅ OK bash: `GNU bash, version 5.3.15(1)-release (x86_64-pc-linux-gnu)`

mason.nvim [Languages] ~
- ✅ OK Ruby: `ruby 3.4.9 (2026-03-11 revision 76cca827ab) +PRISM [x86_64-linux]`
- ✅ OK cargo: `cargo 1.97.0 (c980f4866 2026-06-30)`
- ✅ OK Go: `go version go1.26.5 linux/amd64`
- ✅ OK PHP: `PHP 8.5.9 (cli) (built: Jul 28 2026 13:06:52) (NTS)`
- ✅ OK RubyGem: `3.7.2`
- ⚠️ WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. Could not find executable "javac" in PATH.

- ⚠️ WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. Could not find executable "java" in PATH.

- ⚠️ WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. Could not find executable "julia" in PATH.

- ✅ OK node: `v24.18.1`
- ✅ OK Composer: `Composer version 2.10.2 2026-07-01 11:24:45`
- ✅ OK luarocks: `/nix/store/xbdzyf7nfb5ylzq4b8kxywqaxiq4glrk-lua5.2-luarocks-3.13.0-1/luarocks-3.13.0-1-rocks/luarocks/3.13.0-1/bin/luarocks 3.13.0`
- ✅ OK python: `Python 3.14.6`
- ⚠️ WARNING pip: not available
  - ADVICE:
    - spawn: python3 failed with exit code 1 and signal 0. /run/current-system/sw/bin/python3: No module named pip

- ✅ OK npm: `11.16.0`
- ✅ OK python venv: `Ok`

==============================================================================
mason-lspconfig:                                                            ✅

mason-lspconfig.nvim ~
- ✅ OK Neovim v0.11
- ✅ OK mason.nvim v2

==============================================================================
mcphub:                                                                   4 ⚠️

mcphub.nvim ~
- mcphub.nvim version: 6.2.0
- mcp-hub binary:
- mcp-hub required version: 4.2.1
- mcp-hub installed version: 4.2.1
- ✅ OK mcp-hub version 4.2.1 is compatible

Plugin Dependencies: ~
- ✅ OK plenary.nvim installed

Libraries: ~
- ✅ OK curl installed
- ✅ OK node installed
- ⚠️ WARNING uv not found: Install with `curl -LsSf https://astral.sh/uv/install.sh | sh`

Chat plugins ~
- ⚠️ WARNING codecompanion.nvim not found
- ⚠️ WARNING avante.nvim not found
- ⚠️ WARNING CopilotChat.nvim not found

==============================================================================
noice:                                                                      ✅

noice.nvim ~
- ✅ OK *Neovim* >= 0.9.0
- ✅ OK You're using a GUI that should work ok
- ✅ OK *vim.go.lazyredraw* is not enabled
- ✅ OK `snacks.nvim` is installed
- ✅ OK {TreeSitter} `vim` parser is installed
- ✅ OK {TreeSitter} `regex` parser is installed
- ✅ OK {TreeSitter} `lua` parser is installed
- ✅ OK {TreeSitter} `bash` parser is installed
- ✅ OK {TreeSitter} `markdown` parser is installed
- ✅ OK {TreeSitter} `markdown_inline` parser is installed
- ✅ OK `vim.notify` is set to **Noice**
- ✅ OK `vim.lsp.buf.hover` is set to **Noice**
- ✅ OK `vim.lsp.buf.signature_help` is set to **Noice**
- ✅ OK `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
- ✅ OK `vim.lsp.util.stylize_markdown` is set to **Noice**

==============================================================================
nvim-treesitter:                                                            ✅

Requirements ~
- ✅ OK Neovim was compiled with tree-sitter runtime ABI version 15 (required >=13).
- ✅ OK tree-sitter-cli 0.26.12 (/home/muneeb/.local/share/nvim/mason/bin/tree-sitter)
- ✅ OK tar 1.35.0 (/run/current-system/sw/bin/tar)
- ✅ OK curl 8.21.0 (/etc/profiles/per-user/muneeb/bin/curl)
  curl 8.21.0 (x86_64-pc-linux-gnu) libcurl/8.21.0 OpenSSL/3.6.3 zlib/1.3.2 brotli/1.2.0 zstd/1.5.7 libidn2/2.3.8 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.69.0 ngtcp2/1.23.0 nghttp3/1.16.0 mit-krb5/1.22.2
  Release-Date: 2026-06-24
  Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt mqtts pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
  Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

OS Info ~
- release: 7.1.5-zen1
- machine: x86_64
- version: #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980
- sysname: Linux

Install directory for parsers and queries ~
- /home/muneeb/.local/share/nvim/site
- ✅ OK is writable.
- ✅ OK is in runtimepath.

Installed languages     H L F I J ~
- angular               ✓ ✓ ✓ ✓ ✓
- astro                 ✓ ✓ ✓ ✓ ✓
- bash                  ✓ ✓ ✓ ✓ ✓
- c                     ✓ ✓ ✓ ✓ ✓
- c_sharp               ✓ ✓ ✓ . ✓
- css                   ✓ . ✓ ✓ ✓
- dart                  ✓ ✓ ✓ ✓ ✓
- diff                  ✓ . ✓ . ✓
- dockerfile            ✓ . . . ✓
- dtd                   ✓ ✓ ✓ . ✓
- ecma
- fsharp                ✓ . . . ✓
- git_config            ✓ . ✓ . ✓
- git_rebase            ✓ . . . ✓
- gitattributes         ✓ ✓ . . ✓
- gitcommit             ✓ . . . ✓
- gitignore             ✓ . . . ✓
- go                    ✓ ✓ ✓ ✓ ✓
- gomod                 ✓ . . . ✓
- gosum                 ✓ . . . .
- gowork                ✓ . . . ✓
- graphql               ✓ . . ✓ ✓
- html                  ✓ ✓ ✓ ✓ ✓
- html_tags
- http                  ✓ . ✓ . ✓
- java                  ✓ ✓ ✓ ✓ ✓
- javascript            ✓ ✓ ✓ ✓ ✓
- jsdoc                 ✓ . . . .
- json                  ✓ ✓ ✓ ✓ ✓
- json5                 ✓ . . . ✓
- jsx
- kotlin                ✓ ✓ ✓ . ✓
- lua                   ✓ ✓ ✓ ✓ ✓
- luadoc                ✓ . . . .
- luap                  ✓ . . . .
- markdown              ✓ . ✓ ✓ ✓
- markdown_inline       ✓ . . . ✓
- ninja                 ✓ . ✓ ✓ ✓
- nix                   ✓ ✓ ✓ ✓ ✓
- nu                    ✓ . ✓ ✓ ✓
- php                   ✓ ✓ ✓ ✓ ✓
- php_only              ✓ ✓ ✓ ✓ ✓
- printf                ✓ . . . .
- python                ✓ ✓ ✓ ✓ ✓
- query                 ✓ ✓ ✓ ✓ ✓
- regex                 ✓ . . . .
- ron                   ✓ ✓ ✓ ✓ ✓
- rst                   ✓ ✓ . . ✓
- rust                  ✓ ✓ ✓ ✓ ✓
- scss                  ✓ . ✓ ✓ ✓
- sql                   ✓ . ✓ ✓ ✓
- svelte                ✓ ✓ ✓ ✓ ✓
- toml                  ✓ ✓ ✓ ✓ ✓
- tsx                   ✓ ✓ ✓ ✓ ✓
- twig                  ✓ . . . ✓
- typescript            ✓ ✓ ✓ ✓ ✓
- vim                   ✓ ✓ ✓ . ✓
- vimdoc                ✓ . . . ✓
- xml                   ✓ ✓ ✓ ✓ ✓
- yaml                  ✓ ✓ ✓ ✓ ✓

  Legend: [H]ighlights, [L]ocals, [F]olds, [I]ndents, In[J]ections ~

==============================================================================
overseer:                                                                15 ⚠️

overseer.nvim report ~
- Log file: /home/muneeb/.local/state/nvim/overseer.log
- Log level: WARN
- ⚠️ WARNING {cargo}: No Cargo.toml file found
- ⚠️ WARNING {cargo-make}: Command "cargo-make" not found
- ⚠️ WARNING {composer}: No composer.json file found
- ⚠️ WARNING {deno}: executable deno not found
- ⚠️ WARNING {devenv}: Command "devenv" not found
- ⚠️ WARNING {just}: Command "just" not found
- ⚠️ WARNING {mage}: Command "mage" not found
- ⚠️ WARNING {make}: No Makefile found
- ⚠️ WARNING {mise}: Command "mise" not found
- ⚠️ WARNING {mix}: No mix.exs file found
- ⚠️ WARNING {npm}: No package.json file found
- ⚠️ WARNING {rake}: No Rakefile found
- ⚠️ WARNING {task}: Command "task" not found
- ⚠️ WARNING {tox}: No tox.ini file found
- ⚠️ WARNING {vscode}: No .vscode/tasks.json file found

==============================================================================
sidekick:                                                                12 ⚠️

Sidekick ~
- ✅ OK Using Neovim >= 0.11.2

Sidekick Copilot LSP ~
- ✅ OK Copilot LSP `copilot` is enabled
- ✅ OK Sidekick is handling Copilot LSP status notifications for client: 1

Sidekick AI CLI ~
- ✅ OK autoread is enabled
- ✅ OK Terminal multiplexer integration is disabled
- ✅ OK `tmux` is installed
- ✅ OK `zellij` is not installed, but it's not the configured backend
- ✅ OK `ps` is installed
- ⚠️ WARNING `lsof` is not installed, running processes and ports will not be detected

Sidekick AI CLI Tools ~
- ⚠️ WARNING `aider` is not installed
- ⚠️ WARNING `amazon_q` is not installed
- ⚠️ WARNING `claude` is not installed
- ✅ OK `codex` is installed
- ⚠️ WARNING `copilot` is not installed
- ⚠️ WARNING `crush` is not installed
- ⚠️ WARNING `cursor` is not installed
- ⚠️ WARNING `gemini` is not installed
- ⚠️ WARNING `grok` is not installed
- ⚠️ WARNING `opencode` is not installed
- ⚠️ WARNING `pi` is not installed
- ⚠️ WARNING `qwen` is not installed

==============================================================================
snacks:                                                             8 ⚠️  4 ❌

Snacks ~
- ✅ OK setup called

Snacks.bigfile ~
- ✅ OK setup {enabled}

Snacks.dashboard ~
- ✅ OK setup {enabled}
- ✅ OK setup ran
- ✅ OK dashboard opened

Snacks.explorer ~
- ✅ OK setup {enabled}
- ✅ OK 'gio' `2.88.1`
- ✅ OK System trash command found

Snacks.image ~
- ⚠️ WARNING setup {disabled}
- ✅ OK 'kitty' `kitty 0.48.2 created by Kovid Goyal`
- ✅ OK 'magick' `Version: ImageMagick 7.1.2-29 Q16-HDRI x86_64 b919b37fd:20260727 https://imagemagick.org`
- ✅ OK 'convert' `WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"`
- ✅ OK `kitty` detected and supported
- ✅ OK `kitty` supports unicode placeholders
- ✅ OK Inline images are available
- ✅ OK `tmux` detected and supported
- ✅ OK Terminal Dimensions:
  - {size}: `1898` x `1015` pixels
  - {scale}: `1.62`
  - {cell}: `13` x `29` pixels
- ✅ OK Available Treesitter languages:
    `css`, `html`, `javascript`, `markdown_inline`, `markdown`, `scss`, `svelte`, `tsx`
- ⚠️ WARNING Missing Treesitter languages:
    `latex`, `norg`, `typst`, `vue`
- ⚠️ WARNING Image rendering in docs with missing treesitter parsers won't work
- ❌ ERROR Tool not found: 'gs'
- ⚠️ WARNING `gs` is required to render PDF files
- ❌ ERROR None of the tools found: 'tectonic', 'pdflatex'
- ⚠️ WARNING `tectonic` or `pdflatex` is required to render LaTeX math expressions
- ❌ ERROR Tool not found: 'mmdc'
- ⚠️ WARNING `mmdc` is required to render Mermaid diagrams
- ✅ OK your terminal supports the kitty graphics protocol

Snacks.input ~
- ✅ OK setup {enabled}
- ✅ OK `vim.ui.input` is set to `Snacks.input`

Snacks.lazygit ~
- ❌ ERROR {lazygit} not installed

Snacks.notifier ~
- ✅ OK setup {enabled}
- ✅ OK is ready

Snacks.picker ~
- ✅ OK setup {enabled}
- ✅ OK `vim.ui.select` is set to `Snacks.picker.select`
- ✅ OK Available Treesitter languages:
    `regex`
- ✅ OK 'git' `git version 2.55.0`
- ✅ OK 'rg' `ripgrep 15.2.0`
- ✅ OK `Snacks.picker.grep()` is available
- ✅ OK 'fd' `fd 10.4.2`
- ✅ OK `Snacks.picker.files()` is available
- ✅ OK `Snacks.picker.explorer()` is available
- ⚠️ WARNING `SQLite3` is not available. Frecency and history will be stored in a file instead.

Snacks.quickfile ~
- ✅ OK setup {enabled}

Snacks.scope ~
- ✅ OK setup {enabled}

Snacks.scroll ~
- ✅ OK setup {enabled}

Snacks.statuscolumn ~
- ⚠️ WARNING setup {disabled}

Snacks.terminal ~
- ✅ OK shell configured
  - `vim.o.shell`: /nix/store/l0wcagwxgg5vdsklbci9zf9rh71b0kw4-zsh-5.9.2/bin/zsh
  - `parsed`: { "/nix/store/l0wcagwxgg5vdsklbci9zf9rh71b0kw4-zsh-5.9.2/bin/zsh" }

Snacks.toggle ~
- ✅ OK {which-key} is installed

Snacks.words ~
- ✅ OK setup {enabled}

==============================================================================
vim.deprecated:                                                             ✅

- ✅ OK No deprecated functions detected

==============================================================================
vim.health:                                                                 ✅

System Info ~
- ✅ OK Up to date (0.12.4)
- Nvim version: `v0.12.4` 
- Operating system: Linux 7.1.5-zen1
- Terminal: tmux 3.7b
- $TERM: tmux-256color

Configuration ~
- ✅ OK no issues found

Runtime ~
- ✅ OK $VIMRUNTIME: /nix/store/ynk6nzjgfklnfqw8g6w5a9qk6d9lc7rr-neovim-unwrapped-0.12.4/share/nvim/runtime

Performance ~
- ✅ OK Build type: Release

Remote Plugins ~
- ✅ OK Up to date

Terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"
- $COLORTERM="truecolor"

tmux ~
- ✅ OK escape-time: 10
- ✅ OK focus-events: on
- $TERM: tmux-256color

External Tools ~
- ✅ OK ripgrep 15.2.0 (/etc/profiles/per-user/muneeb/bin/rg)
- ✅ OK vim.ui.open: handler found (xdg-open)
- ✅ OK git version 2.55.0 (/etc/profiles/per-user/muneeb/bin/git)
- ✅ OK curl 8.21.0 (/etc/profiles/per-user/muneeb/bin/curl)
  curl 8.21.0 (x86_64-pc-linux-gnu) libcurl/8.21.0 OpenSSL/3.6.3 zlib/1.3.2 brotli/1.2.0 zstd/1.5.7 libidn2/2.3.8 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.69.0 ngtcp2/1.23.0 nghttp3/1.16.0 mit-krb5/1.22.2
  Release-Date: 2026-06-24
  Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt mqtts pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
  Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

==============================================================================
vim.lsp:                                                                 25 ⚠️

