{ config, pkgs, ... }: {
  home.packages = with pkgs ; [
    nerdfonts
    git
    microsoft-edge
    vim
    neovim
    nodejs-18_x
    gcc
    dotnet-sdk_8
    unzip
    curl
    wget
    dart
    btop
    nvtop
    htop
    docker
    docker-compose
    git
    gh
    github-desktop
    go
    fd
    php
    python3
    ripgrep
    ruby
    rustc
    cargo
    luarocks
    neovim
    lazygit
    zsh
    zsh-autocomplete
    zsh-autopair
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
    xclip
    tmux
    discord
    obs-studio
    qbittorrent
    skypeforlinux
    telegram-desktop
    tigervnc
    vlc
    vscode-fhs
    whatsapp-for-linux
    zoom
    android-studio
    php83Packages.composer
    partition-manager
    libsForQt5.kpmcore
    neofetch
    kitty
    libsForQt5.qtstyleplugin-kvantum
    eza
    nix-init
    figma-linux
    inkscape
    rofi
    dconf
    dconf2nix
    gnome.dconf-editor
    lxappearance
    catppuccin-kvantum
    xfce.thunar
    xfce.thunar-volman
    xfce.thunar-dropbox-plugin
    xfce.thunar-archive-plugin
    xfce.thunar-media-tags-plugin
    xcape
  ];


}
